### ISSUE TITLE
Does it handle the time format?

### ISSUE THREAD

**Issue by youbecha** [nicolashefti/appizy#1]
I uploaded and converted a spreadsheet page that has a table and calculations in a HH:MM format.

It comes out in degrees or some other gibberish.
![Uploading appizy2.jpg…]()
![Uploading appizy1.jpg…]()

**Comment by nicolashefti** [comment]
Indeed, Appizy does not support date format yet. It's part of the idea to be developed when the refactoring phase will be done...
